version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Sidebar.SDK/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "npm"
    directory: "/Acrolinx.Sidebar.SDK/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
    versioning-strategy: increase
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Sidebar.SDK.Setup/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
  - package-ecosystem: "nuget"
    directory: "/Acrolinx.Sidebar.SDK.Test/"
    schedule:
      interval: "daily"
    reviewers:
      - abhijeetnarvekar
